%% MATLAB Script to link softGNSS receiver with gps-sdr-sim output
% This script automatically configures the receiver settings to process 
% the 'gpssim.bin' file generated by the Electron application.

fprintf('Linking softGNSS with Electron project data...\n');

% 1. Get current settings
settings = initSettings();

% 2. Override for Simulation Robustness
% Disable skipping to ensure we start at the beginning of the file
settings.skipNumberOfBytes = 0; 
% Widen acquisition search band to account for high Doppler (up to 10kHz)
settings.acqSearchBand = 10000; 

% Path to the binary file generated by gps-sdr-sim
if ~exist('binPath', 'var')
    binPath = 'C:\Users\Advait Raut\Desktop\gui\temp\gpssim.bin'; % Default fallback
end
settings.fileName = binPath;

% Standard sampling frequency for the simulator's presets (2.6 MHz)
if ~exist('sampRate', 'var')
    sampRate = 2600000; 
end
settings.samplingFreq = sampRate; 

% Data type (8-bit or 16-bit integers for I/Q)
if ~exist('bits', 'var')
    bits = 16;
end

if bits == 8
    settings.dataType = 'int8';
else
    settings.dataType = 'int16';
end

% File Type (2 = 8-bit/16-bit I/Q depending on dataType)
settings.fileType = 2; 

% IF Frequency (gps-sdr-sim uses 0Hz baseband by default)
settings.IF = 0;

fprintf('Configured for: %s (at %g MHz, %d-bit)\n', settings.fileName, settings.samplingFreq/1e6, bits);

%% 3. Start Processing
% Verify file exists before starting
if exist(settings.fileName, 'file')
    fileInfo = dir(settings.fileName);
    fprintf('File Size: %.2f MB\n', fileInfo.bytes / 1e6);
    if fileInfo.bytes == 0
        error('Error: Simulation binary is empty. Please check your generator settings.');
    end
    fprintf('File found. Starting probe and processing...\n');
    
    % Add required paths
    addpath include
    addpath Common
    
    % Probe data for visualization
    probeData(settings);
    
    % Run post-processing
    postProcessing;
    
    % --- Step 4: Export Results to JSON for Electron ---
    if exist('navResults', 'var') && isstruct(navResults) && isfield(navResults, 'latitude')
        % Extract last valid non-NaN position
        validIdx = find(~isnan(navResults.latitude), 1, 'last');
        if ~isempty(validIdx)
            resLat = navResults.latitude(validIdx);
            resLon = navResults.longitude(validIdx);
            
            fprintf('Simulation Result: Lat %.10f, Lon %.10f\n', resLat, resLon);
            
            try
                resPath = 'C:\Users\Advait Raut\Desktop\gui\temp\results.json';
                fid = fopen(resPath, 'w');
                if fid > 0
                    fprintf(fid, '{"lat": %.10f, "lng": %.10f}', resLat, resLon);
                    fclose(fid);
                    fprintf('Coordinates saved to %s\n', resPath);
                end
            catch ME
                fprintf('Error saving results.json: %s\n', ME.message);
            end
        else
            fprintf('Warning: No valid navigation solution found in navResults.\n');
        end
    end
else
    fprintf('Error: %s not found. Please generate the simulation binary first.\n', settings.fileName);
end
